### ISSUE TITLE
Runtime Not Serializing Handler Result to JSON Format

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-aws-lambda#39]
The current APIGatewayProxyResponseEvent.toString() won't serialize itself to JSON, should use a serializer.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Runtime Not Serializing Handler Result to JSON Format light-aws-lambda master](https://trello.com/c/Ai0TBjuJ/936-runtime-not-serializing-handler-result-to-json-format-light-aws-lambda-master)
